In [1]:
import requests 
import pandas as pd
from bs4 import BeautifulSoup as bs

After downloading the needed packages, the data is imported from the Italian renting website immobiliare.it, which lists rent announcements of all italian cities.

In [2]:
r_im = requests.get('https://www.immobiliare.it/mercato-immobiliare/lombardia/milano/') 
soup_im = bs(r_im.content) 

#print('Classes of each table:')
#for table in soup_im.find_all('table'):
#    print(table.get('class'))

tab = soup_im.find('table', class_='nd-table')
immobiliare = pd.read_html(str(tab))[0]
#print(immobiliare)

In [3]:
#changing the column names to English and something more easy to use
immobiliare = immobiliare.rename(columns = {'Vendita(€/m²)':'Sale', 'Affitto(€/m²)' : 'Rent'})

In [4]:
#the rent is written without the decimals, as italian decimal numbers are written with a comma, instead of the dot.
#This function fixes this issue
def fixrent(number):
    n1 = str(number)
    n2 = list(n1)
    n2.insert(2,'.')
    return float(''.join(n2))

print(fixrent(2345))

23.45

In [5]:
immobiliare.Rent = immobiliare.Rent.apply(lambda x: fixrent(x)) #previous function is applied

In [6]:
#same issue with the sales numbers, now fixed
def fixsale(number):
    number = number*1000
    return int(number)

immobiliare.Sale = immobiliare.Sale.apply(lambda x: fixsale(x))
immobiliare

                                    Zone  Sale   Rent
0                                 Centro  9956  29.36
1         Arco della Pace, Arena, Pagano  8922  23.61
2                       Genova, Ticinese  7352  22.58
3         Quadronno, Palestro, Guastalla  8524  24.77
4        Garibaldi, Moscova, Porta Nuova  9479  28.03
5   Fiera, Sempione, City Life, Portello  6616  21.86
6                                Navigli  6056  21.80
7        Porta Romana, Cadore, Montenero  6516  21.16
8            Porta Venezia, Indipendenza  7320  23.31
9                   Centrale, Repubblica  6385  22.74
10                 Cenisio, Sarpi, Isola  6174  22.51
11        Viale Certosa, Cascina Merlata  3745  18.97
12                   Bande Nere, Inganni  4374  17.86
13                     Famagosta, Barona  3977  18.67
14           Abbiategrasso, Chiesa Rossa  4096  19.22
15                  Porta Vittoria, Lodi  4789  19.51
16         Cimiano, Crescenzago, Adriano  3454  17.54
17                     Bicocca, Niguarda  3544  16.94
18                    Solari, Washington  6540  22.90
19                        Affori, Bovisa  3344  18.18
20                      San Siro, Trenno  3605  16.68
21               Bisceglie, Baggio, Olmi  2680  15.50
22                  Ripamonti, Vigentino  4162  18.33
23                             Forlanini  3168  16.19
24                     Città Studi, Susa  5327  19.35
25                    Maggiolina, Istria  4896  18.64
26                       Precotto, Turro  3939  18.46
27                       Udine, Lambrate  4033  17.93
28                     Pasteur, Rovereto  4504  19.93
29            Ponte Lambro, Santa Giulia  2923  15.54
30                    Corvetto, Rogoredo  3695  19.33
31                      Napoli, Soderini  4922  17.84

In [8]:
#immobiliare.to_csv('dataImmobiliare.csv', index=False)